name: The Lycӕum
plugins_dir: ./_plugins
url: http://thelycaeum.in
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
description: Blog posts for the Lycӕum website
author: Noufal Ibrahim
copyright: Copyright Noufal Ibrahim 2013. All rights reserved.

